/*
 * spoonacular API
 *
 * The spoonacular Nutrition, Recipe, and Food API allows you to access over 380,000 recipes, thousands of ingredients, 800,000 food products, and 100,000 menu items. Our food ontology and semantic recipe search engine makes it possible to search for recipes using natural language queries, such as \"gluten free brownies without sugar\" or \"low fat vegan cupcakes.\" You can automatically calculate the nutritional information for any recipe, analyze recipe costs, visualize ingredient lists, find recipes for what's in your fridge, find recipes based on special diets, nutritional requirements, or favorite ingredients, classify recipes into types and cuisines, convert ingredient amounts, or even compute an entire meal plan. With our powerful API, you can create many kinds of food and especially nutrition apps.  Special diets/dietary requirements currently available include: vegan, vegetarian, pescetarian, gluten free, grain free, dairy free, high protein, whole 30, low sodium, low carb, Paleo, ketogenic, FODMAP, and Primal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@spoonacular.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Spoonacular.Api;
using Spoonacular.Model;
using Spoonacular.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Spoonacular.Test.Model
{
    /// <summary>
    ///  Class for testing InlineResponse2001
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2001Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2001
        //private InlineResponse2001 instance;

        public InlineResponse2001Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse2001
            //instance = new InlineResponse2001();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse2001
        /// </summary>
        [Fact]
        public void InlineResponse2001InstanceTest()
        {
            // TODO uncomment below to test "IsType" InlineResponse2001
            //Assert.IsType<InlineResponse2001>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'ImageType'
        /// </summary>
        [Fact]
        public void ImageTypeTest()
        {
            // TODO unit test for the property 'ImageType'
        }
        /// <summary>
        /// Test the property 'Likes'
        /// </summary>
        [Fact]
        public void LikesTest()
        {
            // TODO unit test for the property 'Likes'
        }
        /// <summary>
        /// Test the property 'MissedIngredientCount'
        /// </summary>
        [Fact]
        public void MissedIngredientCountTest()
        {
            // TODO unit test for the property 'MissedIngredientCount'
        }
        /// <summary>
        /// Test the property 'MissedIngredients'
        /// </summary>
        [Fact]
        public void MissedIngredientsTest()
        {
            // TODO unit test for the property 'MissedIngredients'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'UnusedIngredients'
        /// </summary>
        [Fact]
        public void UnusedIngredientsTest()
        {
            // TODO unit test for the property 'UnusedIngredients'
        }
        /// <summary>
        /// Test the property 'UsedIngredientCount'
        /// </summary>
        [Fact]
        public void UsedIngredientCountTest()
        {
            // TODO unit test for the property 'UsedIngredientCount'
        }
        /// <summary>
        /// Test the property 'UsedIngredients'
        /// </summary>
        [Fact]
        public void UsedIngredientsTest()
        {
            // TODO unit test for the property 'UsedIngredients'
        }

    }

}
