/*
 * spoonacular API
 *
 * The spoonacular Nutrition, Recipe, and Food API allows you to access over 380,000 recipes, thousands of ingredients, 800,000 food products, and 100,000 menu items. Our food ontology and semantic recipe search engine makes it possible to search for recipes using natural language queries, such as \"gluten free brownies without sugar\" or \"low fat vegan cupcakes.\" You can automatically calculate the nutritional information for any recipe, analyze recipe costs, visualize ingredient lists, find recipes for what's in your fridge, find recipes based on special diets, nutritional requirements, or favorite ingredients, classify recipes into types and cuisines, convert ingredient amounts, or even compute an entire meal plan. With our powerful API, you can create many kinds of food and especially nutrition apps.  Special diets/dietary requirements currently available include: vegan, vegetarian, pescetarian, gluten free, grain free, dairy free, high protein, whole 30, low sodium, low carb, Paleo, ketogenic, FODMAP, and Primal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@spoonacular.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Spoonacular.Api;
using Spoonacular.Model;
using Spoonacular.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Spoonacular.Test.Model
{
    /// <summary>
    ///  Class for testing InlineResponse2003WinePairingProductMatches
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2003WinePairingProductMatchesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2003WinePairingProductMatches
        //private InlineResponse2003WinePairingProductMatches instance;

        public InlineResponse2003WinePairingProductMatchesTests()
        {
            // TODO uncomment below to create an instance of InlineResponse2003WinePairingProductMatches
            //instance = new InlineResponse2003WinePairingProductMatches();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse2003WinePairingProductMatches
        /// </summary>
        [Fact]
        public void InlineResponse2003WinePairingProductMatchesInstanceTest()
        {
            // TODO uncomment below to test "IsType" InlineResponse2003WinePairingProductMatches
            //Assert.IsType<InlineResponse2003WinePairingProductMatches>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'ImageUrl'
        /// </summary>
        [Fact]
        public void ImageUrlTest()
        {
            // TODO unit test for the property 'ImageUrl'
        }
        /// <summary>
        /// Test the property 'AverageRating'
        /// </summary>
        [Fact]
        public void AverageRatingTest()
        {
            // TODO unit test for the property 'AverageRating'
        }
        /// <summary>
        /// Test the property 'RatingCount'
        /// </summary>
        [Fact]
        public void RatingCountTest()
        {
            // TODO unit test for the property 'RatingCount'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Fact]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
        /// <summary>
        /// Test the property 'Link'
        /// </summary>
        [Fact]
        public void LinkTest()
        {
            // TODO unit test for the property 'Link'
        }

    }

}
