/*
 * spoonacular API
 *
 * The spoonacular Nutrition, Recipe, and Food API allows you to access over 380,000 recipes, thousands of ingredients, 800,000 food products, and 100,000 menu items. Our food ontology and semantic recipe search engine makes it possible to search for recipes using natural language queries, such as \"gluten free brownies without sugar\" or \"low fat vegan cupcakes.\" You can automatically calculate the nutritional information for any recipe, analyze recipe costs, visualize ingredient lists, find recipes for what's in your fridge, find recipes based on special diets, nutritional requirements, or favorite ingredients, classify recipes into types and cuisines, convert ingredient amounts, or even compute an entire meal plan. With our powerful API, you can create many kinds of food and especially nutrition apps.  Special diets/dietary requirements currently available include: vegan, vegetarian, pescetarian, gluten free, grain free, dairy free, high protein, whole 30, low sodium, low carb, Paleo, ketogenic, FODMAP, and Primal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@spoonacular.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Spoonacular.Api;
using Spoonacular.Model;
using Spoonacular.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Spoonacular.Test.Model
{
    /// <summary>
    ///  Class for testing InlineResponse2002
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2002Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2002
        //private InlineResponse2002 instance;

        public InlineResponse2002Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse2002
            //instance = new InlineResponse2002();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse2002
        /// </summary>
        [Fact]
        public void InlineResponse2002InstanceTest()
        {
            // TODO uncomment below to test "IsType" InlineResponse2002
            //Assert.IsType<InlineResponse2002>(instance);
        }


        /// <summary>
        /// Test the property 'Calories'
        /// </summary>
        [Fact]
        public void CaloriesTest()
        {
            // TODO unit test for the property 'Calories'
        }
        /// <summary>
        /// Test the property 'Carbs'
        /// </summary>
        [Fact]
        public void CarbsTest()
        {
            // TODO unit test for the property 'Carbs'
        }
        /// <summary>
        /// Test the property 'Fat'
        /// </summary>
        [Fact]
        public void FatTest()
        {
            // TODO unit test for the property 'Fat'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'ImageType'
        /// </summary>
        [Fact]
        public void ImageTypeTest()
        {
            // TODO unit test for the property 'ImageType'
        }
        /// <summary>
        /// Test the property 'Protein'
        /// </summary>
        [Fact]
        public void ProteinTest()
        {
            // TODO unit test for the property 'Protein'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
