/*
 * spoonacular API
 *
 * The spoonacular Nutrition, Recipe, and Food API allows you to access over 380,000 recipes, thousands of ingredients, 800,000 food products, and 100,000 menu items. Our food ontology and semantic recipe search engine makes it possible to search for recipes using natural language queries, such as \"gluten free brownies without sugar\" or \"low fat vegan cupcakes.\" You can automatically calculate the nutritional information for any recipe, analyze recipe costs, visualize ingredient lists, find recipes for what's in your fridge, find recipes based on special diets, nutritional requirements, or favorite ingredients, classify recipes into types and cuisines, convert ingredient amounts, or even compute an entire meal plan. With our powerful API, you can create many kinds of food and especially nutrition apps.  Special diets/dietary requirements currently available include: vegan, vegetarian, pescetarian, gluten free, grain free, dairy free, high protein, whole 30, low sodium, low carb, Paleo, ketogenic, FODMAP, and Primal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@spoonacular.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Spoonacular.Client.OpenAPIDateConverter;

namespace Spoonacular.Model
{
    /// <summary>
    /// InlineResponse20020
    /// </summary>
    [DataContract(Name = "inline_response_200_20")]
    public partial class InlineResponse20020 : IEquatable<InlineResponse20020>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20020" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineResponse20020() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20020" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="original">original (required).</param>
        /// <param name="originalName">originalName (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="nameClean">nameClean (required).</param>
        /// <param name="amount">amount (required).</param>
        /// <param name="unit">unit (required).</param>
        /// <param name="unitShort">unitShort (required).</param>
        /// <param name="unitLong">unitLong (required).</param>
        /// <param name="possibleUnits">possibleUnits (required).</param>
        /// <param name="estimatedCost">estimatedCost (required).</param>
        /// <param name="consistency">consistency (required).</param>
        /// <param name="aisle">aisle (required).</param>
        /// <param name="image">image (required).</param>
        /// <param name="meta">meta (required).</param>
        /// <param name="nutrition">nutrition (required).</param>
        public InlineResponse20020(int id = default(int), string original = default(string), string originalName = default(string), string name = default(string), string nameClean = default(string), decimal amount = default(decimal), string unit = default(string), string unitShort = default(string), string unitLong = default(string), List<string> possibleUnits = default(List<string>), RecipesParseIngredientsEstimatedCost estimatedCost = default(RecipesParseIngredientsEstimatedCost), string consistency = default(string), string aisle = default(string), string image = default(string), List<string> meta = default(List<string>), RecipesParseIngredientsNutrition nutrition = default(RecipesParseIngredientsNutrition))
        {
            this.Id = id;
            // to ensure "original" is required (not null)
            if (original == null)
            {
                throw new ArgumentNullException("original is a required property for InlineResponse20020 and cannot be null");
            }
            this.Original = original;
            // to ensure "originalName" is required (not null)
            if (originalName == null)
            {
                throw new ArgumentNullException("originalName is a required property for InlineResponse20020 and cannot be null");
            }
            this.OriginalName = originalName;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for InlineResponse20020 and cannot be null");
            }
            this.Name = name;
            // to ensure "nameClean" is required (not null)
            if (nameClean == null)
            {
                throw new ArgumentNullException("nameClean is a required property for InlineResponse20020 and cannot be null");
            }
            this.NameClean = nameClean;
            this.Amount = amount;
            // to ensure "unit" is required (not null)
            if (unit == null)
            {
                throw new ArgumentNullException("unit is a required property for InlineResponse20020 and cannot be null");
            }
            this.Unit = unit;
            // to ensure "unitShort" is required (not null)
            if (unitShort == null)
            {
                throw new ArgumentNullException("unitShort is a required property for InlineResponse20020 and cannot be null");
            }
            this.UnitShort = unitShort;
            // to ensure "unitLong" is required (not null)
            if (unitLong == null)
            {
                throw new ArgumentNullException("unitLong is a required property for InlineResponse20020 and cannot be null");
            }
            this.UnitLong = unitLong;
            // to ensure "possibleUnits" is required (not null)
            if (possibleUnits == null)
            {
                throw new ArgumentNullException("possibleUnits is a required property for InlineResponse20020 and cannot be null");
            }
            this.PossibleUnits = possibleUnits;
            // to ensure "estimatedCost" is required (not null)
            if (estimatedCost == null)
            {
                throw new ArgumentNullException("estimatedCost is a required property for InlineResponse20020 and cannot be null");
            }
            this.EstimatedCost = estimatedCost;
            // to ensure "consistency" is required (not null)
            if (consistency == null)
            {
                throw new ArgumentNullException("consistency is a required property for InlineResponse20020 and cannot be null");
            }
            this.Consistency = consistency;
            // to ensure "aisle" is required (not null)
            if (aisle == null)
            {
                throw new ArgumentNullException("aisle is a required property for InlineResponse20020 and cannot be null");
            }
            this.Aisle = aisle;
            // to ensure "image" is required (not null)
            if (image == null)
            {
                throw new ArgumentNullException("image is a required property for InlineResponse20020 and cannot be null");
            }
            this.Image = image;
            // to ensure "meta" is required (not null)
            if (meta == null)
            {
                throw new ArgumentNullException("meta is a required property for InlineResponse20020 and cannot be null");
            }
            this.Meta = meta;
            // to ensure "nutrition" is required (not null)
            if (nutrition == null)
            {
                throw new ArgumentNullException("nutrition is a required property for InlineResponse20020 and cannot be null");
            }
            this.Nutrition = nutrition;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Original
        /// </summary>
        [DataMember(Name = "original", IsRequired = true, EmitDefaultValue = false)]
        public string Original { get; set; }

        /// <summary>
        /// Gets or Sets OriginalName
        /// </summary>
        [DataMember(Name = "originalName", IsRequired = true, EmitDefaultValue = false)]
        public string OriginalName { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets NameClean
        /// </summary>
        [DataMember(Name = "nameClean", IsRequired = true, EmitDefaultValue = false)]
        public string NameClean { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = false)]
        public decimal Amount { get; set; }

        /// <summary>
        /// Gets or Sets Unit
        /// </summary>
        [DataMember(Name = "unit", IsRequired = true, EmitDefaultValue = false)]
        public string Unit { get; set; }

        /// <summary>
        /// Gets or Sets UnitShort
        /// </summary>
        [DataMember(Name = "unitShort", IsRequired = true, EmitDefaultValue = false)]
        public string UnitShort { get; set; }

        /// <summary>
        /// Gets or Sets UnitLong
        /// </summary>
        [DataMember(Name = "unitLong", IsRequired = true, EmitDefaultValue = false)]
        public string UnitLong { get; set; }

        /// <summary>
        /// Gets or Sets PossibleUnits
        /// </summary>
        [DataMember(Name = "possibleUnits", IsRequired = true, EmitDefaultValue = false)]
        public List<string> PossibleUnits { get; set; }

        /// <summary>
        /// Gets or Sets EstimatedCost
        /// </summary>
        [DataMember(Name = "estimatedCost", IsRequired = true, EmitDefaultValue = false)]
        public RecipesParseIngredientsEstimatedCost EstimatedCost { get; set; }

        /// <summary>
        /// Gets or Sets Consistency
        /// </summary>
        [DataMember(Name = "consistency", IsRequired = true, EmitDefaultValue = false)]
        public string Consistency { get; set; }

        /// <summary>
        /// Gets or Sets Aisle
        /// </summary>
        [DataMember(Name = "aisle", IsRequired = true, EmitDefaultValue = false)]
        public string Aisle { get; set; }

        /// <summary>
        /// Gets or Sets Image
        /// </summary>
        [DataMember(Name = "image", IsRequired = true, EmitDefaultValue = false)]
        public string Image { get; set; }

        /// <summary>
        /// Gets or Sets Meta
        /// </summary>
        [DataMember(Name = "meta", IsRequired = true, EmitDefaultValue = false)]
        public List<string> Meta { get; set; }

        /// <summary>
        /// Gets or Sets Nutrition
        /// </summary>
        [DataMember(Name = "nutrition", IsRequired = true, EmitDefaultValue = false)]
        public RecipesParseIngredientsNutrition Nutrition { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InlineResponse20020 {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Original: ").Append(Original).Append("\n");
            sb.Append("  OriginalName: ").Append(OriginalName).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  NameClean: ").Append(NameClean).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Unit: ").Append(Unit).Append("\n");
            sb.Append("  UnitShort: ").Append(UnitShort).Append("\n");
            sb.Append("  UnitLong: ").Append(UnitLong).Append("\n");
            sb.Append("  PossibleUnits: ").Append(PossibleUnits).Append("\n");
            sb.Append("  EstimatedCost: ").Append(EstimatedCost).Append("\n");
            sb.Append("  Consistency: ").Append(Consistency).Append("\n");
            sb.Append("  Aisle: ").Append(Aisle).Append("\n");
            sb.Append("  Image: ").Append(Image).Append("\n");
            sb.Append("  Meta: ").Append(Meta).Append("\n");
            sb.Append("  Nutrition: ").Append(Nutrition).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse20020);
        }

        /// <summary>
        /// Returns true if InlineResponse20020 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse20020 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20020 input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.Original == input.Original ||
                    (this.Original != null &&
                    this.Original.Equals(input.Original))
                ) && 
                (
                    this.OriginalName == input.OriginalName ||
                    (this.OriginalName != null &&
                    this.OriginalName.Equals(input.OriginalName))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.NameClean == input.NameClean ||
                    (this.NameClean != null &&
                    this.NameClean.Equals(input.NameClean))
                ) && 
                (
                    this.Amount == input.Amount ||
                    this.Amount.Equals(input.Amount)
                ) && 
                (
                    this.Unit == input.Unit ||
                    (this.Unit != null &&
                    this.Unit.Equals(input.Unit))
                ) && 
                (
                    this.UnitShort == input.UnitShort ||
                    (this.UnitShort != null &&
                    this.UnitShort.Equals(input.UnitShort))
                ) && 
                (
                    this.UnitLong == input.UnitLong ||
                    (this.UnitLong != null &&
                    this.UnitLong.Equals(input.UnitLong))
                ) && 
                (
                    this.PossibleUnits == input.PossibleUnits ||
                    this.PossibleUnits != null &&
                    input.PossibleUnits != null &&
                    this.PossibleUnits.SequenceEqual(input.PossibleUnits)
                ) && 
                (
                    this.EstimatedCost == input.EstimatedCost ||
                    (this.EstimatedCost != null &&
                    this.EstimatedCost.Equals(input.EstimatedCost))
                ) && 
                (
                    this.Consistency == input.Consistency ||
                    (this.Consistency != null &&
                    this.Consistency.Equals(input.Consistency))
                ) && 
                (
                    this.Aisle == input.Aisle ||
                    (this.Aisle != null &&
                    this.Aisle.Equals(input.Aisle))
                ) && 
                (
                    this.Image == input.Image ||
                    (this.Image != null &&
                    this.Image.Equals(input.Image))
                ) && 
                (
                    this.Meta == input.Meta ||
                    this.Meta != null &&
                    input.Meta != null &&
                    this.Meta.SequenceEqual(input.Meta)
                ) && 
                (
                    this.Nutrition == input.Nutrition ||
                    (this.Nutrition != null &&
                    this.Nutrition.Equals(input.Nutrition))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Id.GetHashCode();
                if (this.Original != null)
                {
                    hashCode = (hashCode * 59) + this.Original.GetHashCode();
                }
                if (this.OriginalName != null)
                {
                    hashCode = (hashCode * 59) + this.OriginalName.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.NameClean != null)
                {
                    hashCode = (hashCode * 59) + this.NameClean.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Amount.GetHashCode();
                if (this.Unit != null)
                {
                    hashCode = (hashCode * 59) + this.Unit.GetHashCode();
                }
                if (this.UnitShort != null)
                {
                    hashCode = (hashCode * 59) + this.UnitShort.GetHashCode();
                }
                if (this.UnitLong != null)
                {
                    hashCode = (hashCode * 59) + this.UnitLong.GetHashCode();
                }
                if (this.PossibleUnits != null)
                {
                    hashCode = (hashCode * 59) + this.PossibleUnits.GetHashCode();
                }
                if (this.EstimatedCost != null)
                {
                    hashCode = (hashCode * 59) + this.EstimatedCost.GetHashCode();
                }
                if (this.Consistency != null)
                {
                    hashCode = (hashCode * 59) + this.Consistency.GetHashCode();
                }
                if (this.Aisle != null)
                {
                    hashCode = (hashCode * 59) + this.Aisle.GetHashCode();
                }
                if (this.Image != null)
                {
                    hashCode = (hashCode * 59) + this.Image.GetHashCode();
                }
                if (this.Meta != null)
                {
                    hashCode = (hashCode * 59) + this.Meta.GetHashCode();
                }
                if (this.Nutrition != null)
                {
                    hashCode = (hashCode * 59) + this.Nutrition.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // Original (string) minLength
            if (this.Original != null && this.Original.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Original, length must be greater than 1.", new [] { "Original" });
            }

            // OriginalName (string) minLength
            if (this.OriginalName != null && this.OriginalName.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for OriginalName, length must be greater than 1.", new [] { "OriginalName" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // NameClean (string) minLength
            if (this.NameClean != null && this.NameClean.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for NameClean, length must be greater than 1.", new [] { "NameClean" });
            }

            // Unit (string) minLength
            if (this.Unit != null && this.Unit.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Unit, length must be greater than 1.", new [] { "Unit" });
            }

            // UnitShort (string) minLength
            if (this.UnitShort != null && this.UnitShort.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for UnitShort, length must be greater than 1.", new [] { "UnitShort" });
            }

            // UnitLong (string) minLength
            if (this.UnitLong != null && this.UnitLong.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for UnitLong, length must be greater than 1.", new [] { "UnitLong" });
            }

            // Consistency (string) minLength
            if (this.Consistency != null && this.Consistency.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Consistency, length must be greater than 1.", new [] { "Consistency" });
            }

            // Aisle (string) minLength
            if (this.Aisle != null && this.Aisle.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Aisle, length must be greater than 1.", new [] { "Aisle" });
            }

            // Image (string) minLength
            if (this.Image != null && this.Image.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Image, length must be greater than 1.", new [] { "Image" });
            }

            yield break;
        }
    }

}
