/*
 * spoonacular API
 *
 * The spoonacular Nutrition, Recipe, and Food API allows you to access over 380,000 recipes, thousands of ingredients, 800,000 food products, and 100,000 menu items. Our food ontology and semantic recipe search engine makes it possible to search for recipes using natural language queries, such as \"gluten free brownies without sugar\" or \"low fat vegan cupcakes.\" You can automatically calculate the nutritional information for any recipe, analyze recipe costs, visualize ingredient lists, find recipes for what's in your fridge, find recipes based on special diets, nutritional requirements, or favorite ingredients, classify recipes into types and cuisines, convert ingredient amounts, or even compute an entire meal plan. With our powerful API, you can create many kinds of food and especially nutrition apps.  Special diets/dietary requirements currently available include: vegan, vegetarian, pescetarian, gluten free, grain free, dairy free, high protein, whole 30, low sodium, low carb, Paleo, ketogenic, FODMAP, and Primal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@spoonacular.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Spoonacular.Client.OpenAPIDateConverter;

namespace Spoonacular.Model
{
    /// <summary>
    /// InlineResponse20018
    /// </summary>
    [DataContract(Name = "inline_response_200_18")]
    public partial class InlineResponse20018 : IEquatable<InlineResponse20018>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20018" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineResponse20018() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20018" /> class.
        /// </summary>
        /// <param name="dishes">dishes (required).</param>
        /// <param name="ingredients">ingredients (required).</param>
        /// <param name="cuisines">cuisines (required).</param>
        /// <param name="modifiers">modifiers (required).</param>
        public InlineResponse20018(List<InlineResponse20018Dishes> dishes = default(List<InlineResponse20018Dishes>), List<InlineResponse20018Ingredients> ingredients = default(List<InlineResponse20018Ingredients>), List<string> cuisines = default(List<string>), List<string> modifiers = default(List<string>))
        {
            // to ensure "dishes" is required (not null)
            if (dishes == null)
            {
                throw new ArgumentNullException("dishes is a required property for InlineResponse20018 and cannot be null");
            }
            this.Dishes = dishes;
            // to ensure "ingredients" is required (not null)
            if (ingredients == null)
            {
                throw new ArgumentNullException("ingredients is a required property for InlineResponse20018 and cannot be null");
            }
            this.Ingredients = ingredients;
            // to ensure "cuisines" is required (not null)
            if (cuisines == null)
            {
                throw new ArgumentNullException("cuisines is a required property for InlineResponse20018 and cannot be null");
            }
            this.Cuisines = cuisines;
            // to ensure "modifiers" is required (not null)
            if (modifiers == null)
            {
                throw new ArgumentNullException("modifiers is a required property for InlineResponse20018 and cannot be null");
            }
            this.Modifiers = modifiers;
        }

        /// <summary>
        /// Gets or Sets Dishes
        /// </summary>
        [DataMember(Name = "dishes", IsRequired = true, EmitDefaultValue = false)]
        public List<InlineResponse20018Dishes> Dishes { get; set; }

        /// <summary>
        /// Gets or Sets Ingredients
        /// </summary>
        [DataMember(Name = "ingredients", IsRequired = true, EmitDefaultValue = false)]
        public List<InlineResponse20018Ingredients> Ingredients { get; set; }

        /// <summary>
        /// Gets or Sets Cuisines
        /// </summary>
        [DataMember(Name = "cuisines", IsRequired = true, EmitDefaultValue = false)]
        public List<string> Cuisines { get; set; }

        /// <summary>
        /// Gets or Sets Modifiers
        /// </summary>
        [DataMember(Name = "modifiers", IsRequired = true, EmitDefaultValue = false)]
        public List<string> Modifiers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InlineResponse20018 {\n");
            sb.Append("  Dishes: ").Append(Dishes).Append("\n");
            sb.Append("  Ingredients: ").Append(Ingredients).Append("\n");
            sb.Append("  Cuisines: ").Append(Cuisines).Append("\n");
            sb.Append("  Modifiers: ").Append(Modifiers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse20018);
        }

        /// <summary>
        /// Returns true if InlineResponse20018 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse20018 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20018 input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Dishes == input.Dishes ||
                    this.Dishes != null &&
                    input.Dishes != null &&
                    this.Dishes.SequenceEqual(input.Dishes)
                ) && 
                (
                    this.Ingredients == input.Ingredients ||
                    this.Ingredients != null &&
                    input.Ingredients != null &&
                    this.Ingredients.SequenceEqual(input.Ingredients)
                ) && 
                (
                    this.Cuisines == input.Cuisines ||
                    this.Cuisines != null &&
                    input.Cuisines != null &&
                    this.Cuisines.SequenceEqual(input.Cuisines)
                ) && 
                (
                    this.Modifiers == input.Modifiers ||
                    this.Modifiers != null &&
                    input.Modifiers != null &&
                    this.Modifiers.SequenceEqual(input.Modifiers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Dishes != null)
                {
                    hashCode = (hashCode * 59) + this.Dishes.GetHashCode();
                }
                if (this.Ingredients != null)
                {
                    hashCode = (hashCode * 59) + this.Ingredients.GetHashCode();
                }
                if (this.Cuisines != null)
                {
                    hashCode = (hashCode * 59) + this.Cuisines.GetHashCode();
                }
                if (this.Modifiers != null)
                {
                    hashCode = (hashCode * 59) + this.Modifiers.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
