/*
 * spoonacular API
 *
 * The spoonacular Nutrition, Recipe, and Food API allows you to access over 380,000 recipes, thousands of ingredients, 800,000 food products, and 100,000 menu items. Our food ontology and semantic recipe search engine makes it possible to search for recipes using natural language queries, such as \"gluten free brownies without sugar\" or \"low fat vegan cupcakes.\" You can automatically calculate the nutritional information for any recipe, analyze recipe costs, visualize ingredient lists, find recipes for what's in your fridge, find recipes based on special diets, nutritional requirements, or favorite ingredients, classify recipes into types and cuisines, convert ingredient amounts, or even compute an entire meal plan. With our powerful API, you can create many kinds of food and especially nutrition apps.  Special diets/dietary requirements currently available include: vegan, vegetarian, pescetarian, gluten free, grain free, dairy free, high protein, whole 30, low sodium, low carb, Paleo, ketogenic, FODMAP, and Primal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@spoonacular.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Spoonacular.Client.OpenAPIDateConverter;

namespace Spoonacular.Model
{
    /// <summary>
    /// InlineResponse20019
    /// </summary>
    [DataContract(Name = "inline_response_200_19")]
    public partial class InlineResponse20019 : IEquatable<InlineResponse20019>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20019" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineResponse20019() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20019" /> class.
        /// </summary>
        /// <param name="sourceAmount">sourceAmount (required).</param>
        /// <param name="sourceUnit">sourceUnit (required).</param>
        /// <param name="targetAmount">targetAmount (required).</param>
        /// <param name="targetUnit">targetUnit (required).</param>
        /// <param name="answer">answer (required).</param>
        public InlineResponse20019(decimal sourceAmount = default(decimal), string sourceUnit = default(string), decimal targetAmount = default(decimal), string targetUnit = default(string), string answer = default(string))
        {
            this.SourceAmount = sourceAmount;
            // to ensure "sourceUnit" is required (not null)
            if (sourceUnit == null)
            {
                throw new ArgumentNullException("sourceUnit is a required property for InlineResponse20019 and cannot be null");
            }
            this.SourceUnit = sourceUnit;
            this.TargetAmount = targetAmount;
            // to ensure "targetUnit" is required (not null)
            if (targetUnit == null)
            {
                throw new ArgumentNullException("targetUnit is a required property for InlineResponse20019 and cannot be null");
            }
            this.TargetUnit = targetUnit;
            // to ensure "answer" is required (not null)
            if (answer == null)
            {
                throw new ArgumentNullException("answer is a required property for InlineResponse20019 and cannot be null");
            }
            this.Answer = answer;
        }

        /// <summary>
        /// Gets or Sets SourceAmount
        /// </summary>
        [DataMember(Name = "sourceAmount", IsRequired = true, EmitDefaultValue = false)]
        public decimal SourceAmount { get; set; }

        /// <summary>
        /// Gets or Sets SourceUnit
        /// </summary>
        [DataMember(Name = "sourceUnit", IsRequired = true, EmitDefaultValue = false)]
        public string SourceUnit { get; set; }

        /// <summary>
        /// Gets or Sets TargetAmount
        /// </summary>
        [DataMember(Name = "targetAmount", IsRequired = true, EmitDefaultValue = false)]
        public decimal TargetAmount { get; set; }

        /// <summary>
        /// Gets or Sets TargetUnit
        /// </summary>
        [DataMember(Name = "targetUnit", IsRequired = true, EmitDefaultValue = false)]
        public string TargetUnit { get; set; }

        /// <summary>
        /// Gets or Sets Answer
        /// </summary>
        [DataMember(Name = "answer", IsRequired = true, EmitDefaultValue = false)]
        public string Answer { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InlineResponse20019 {\n");
            sb.Append("  SourceAmount: ").Append(SourceAmount).Append("\n");
            sb.Append("  SourceUnit: ").Append(SourceUnit).Append("\n");
            sb.Append("  TargetAmount: ").Append(TargetAmount).Append("\n");
            sb.Append("  TargetUnit: ").Append(TargetUnit).Append("\n");
            sb.Append("  Answer: ").Append(Answer).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse20019);
        }

        /// <summary>
        /// Returns true if InlineResponse20019 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse20019 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20019 input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SourceAmount == input.SourceAmount ||
                    this.SourceAmount.Equals(input.SourceAmount)
                ) && 
                (
                    this.SourceUnit == input.SourceUnit ||
                    (this.SourceUnit != null &&
                    this.SourceUnit.Equals(input.SourceUnit))
                ) && 
                (
                    this.TargetAmount == input.TargetAmount ||
                    this.TargetAmount.Equals(input.TargetAmount)
                ) && 
                (
                    this.TargetUnit == input.TargetUnit ||
                    (this.TargetUnit != null &&
                    this.TargetUnit.Equals(input.TargetUnit))
                ) && 
                (
                    this.Answer == input.Answer ||
                    (this.Answer != null &&
                    this.Answer.Equals(input.Answer))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.SourceAmount.GetHashCode();
                if (this.SourceUnit != null)
                {
                    hashCode = (hashCode * 59) + this.SourceUnit.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.TargetAmount.GetHashCode();
                if (this.TargetUnit != null)
                {
                    hashCode = (hashCode * 59) + this.TargetUnit.GetHashCode();
                }
                if (this.Answer != null)
                {
                    hashCode = (hashCode * 59) + this.Answer.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // SourceUnit (string) minLength
            if (this.SourceUnit != null && this.SourceUnit.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SourceUnit, length must be greater than 1.", new [] { "SourceUnit" });
            }

            // TargetUnit (string) minLength
            if (this.TargetUnit != null && this.TargetUnit.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TargetUnit, length must be greater than 1.", new [] { "TargetUnit" });
            }

            // Answer (string) minLength
            if (this.Answer != null && this.Answer.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Answer, length must be greater than 1.", new [] { "Answer" });
            }

            yield break;
        }
    }

}
