/*
 * spoonacular API
 *
 * The spoonacular Nutrition, Recipe, and Food API allows you to access over 380,000 recipes, thousands of ingredients, 800,000 food products, and 100,000 menu items. Our food ontology and semantic recipe search engine makes it possible to search for recipes using natural language queries, such as \"gluten free brownies without sugar\" or \"low fat vegan cupcakes.\" You can automatically calculate the nutritional information for any recipe, analyze recipe costs, visualize ingredient lists, find recipes for what's in your fridge, find recipes based on special diets, nutritional requirements, or favorite ingredients, classify recipes into types and cuisines, convert ingredient amounts, or even compute an entire meal plan. With our powerful API, you can create many kinds of food and especially nutrition apps.  Special diets/dietary requirements currently available include: vegan, vegetarian, pescetarian, gluten free, grain free, dairy free, high protein, whole 30, low sodium, low carb, Paleo, ketogenic, FODMAP, and Primal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@spoonacular.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Spoonacular.Client.OpenAPIDateConverter;

namespace Spoonacular.Model
{
    /// <summary>
    /// InlineResponse20012
    /// </summary>
    [DataContract(Name = "inline_response_200_12")]
    public partial class InlineResponse20012 : IEquatable<InlineResponse20012>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20012" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineResponse20012() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20012" /> class.
        /// </summary>
        /// <param name="calories">calories (required).</param>
        /// <param name="carbs">carbs (required).</param>
        /// <param name="fat">fat (required).</param>
        /// <param name="protein">protein (required).</param>
        /// <param name="bad">bad (required).</param>
        /// <param name="good">good (required).</param>
        public InlineResponse20012(string calories = default(string), string carbs = default(string), string fat = default(string), string protein = default(string), List<Object> bad = default(List<Object>), List<Object> good = default(List<Object>))
        {
            // to ensure "calories" is required (not null)
            if (calories == null)
            {
                throw new ArgumentNullException("calories is a required property for InlineResponse20012 and cannot be null");
            }
            this.Calories = calories;
            // to ensure "carbs" is required (not null)
            if (carbs == null)
            {
                throw new ArgumentNullException("carbs is a required property for InlineResponse20012 and cannot be null");
            }
            this.Carbs = carbs;
            // to ensure "fat" is required (not null)
            if (fat == null)
            {
                throw new ArgumentNullException("fat is a required property for InlineResponse20012 and cannot be null");
            }
            this.Fat = fat;
            // to ensure "protein" is required (not null)
            if (protein == null)
            {
                throw new ArgumentNullException("protein is a required property for InlineResponse20012 and cannot be null");
            }
            this.Protein = protein;
            // to ensure "bad" is required (not null)
            if (bad == null)
            {
                throw new ArgumentNullException("bad is a required property for InlineResponse20012 and cannot be null");
            }
            this.Bad = bad;
            // to ensure "good" is required (not null)
            if (good == null)
            {
                throw new ArgumentNullException("good is a required property for InlineResponse20012 and cannot be null");
            }
            this.Good = good;
        }

        /// <summary>
        /// Gets or Sets Calories
        /// </summary>
        [DataMember(Name = "calories", IsRequired = true, EmitDefaultValue = false)]
        public string Calories { get; set; }

        /// <summary>
        /// Gets or Sets Carbs
        /// </summary>
        [DataMember(Name = "carbs", IsRequired = true, EmitDefaultValue = false)]
        public string Carbs { get; set; }

        /// <summary>
        /// Gets or Sets Fat
        /// </summary>
        [DataMember(Name = "fat", IsRequired = true, EmitDefaultValue = false)]
        public string Fat { get; set; }

        /// <summary>
        /// Gets or Sets Protein
        /// </summary>
        [DataMember(Name = "protein", IsRequired = true, EmitDefaultValue = false)]
        public string Protein { get; set; }

        /// <summary>
        /// Gets or Sets Bad
        /// </summary>
        [DataMember(Name = "bad", IsRequired = true, EmitDefaultValue = false)]
        public List<Object> Bad { get; set; }

        /// <summary>
        /// Gets or Sets Good
        /// </summary>
        [DataMember(Name = "good", IsRequired = true, EmitDefaultValue = false)]
        public List<Object> Good { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InlineResponse20012 {\n");
            sb.Append("  Calories: ").Append(Calories).Append("\n");
            sb.Append("  Carbs: ").Append(Carbs).Append("\n");
            sb.Append("  Fat: ").Append(Fat).Append("\n");
            sb.Append("  Protein: ").Append(Protein).Append("\n");
            sb.Append("  Bad: ").Append(Bad).Append("\n");
            sb.Append("  Good: ").Append(Good).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse20012);
        }

        /// <summary>
        /// Returns true if InlineResponse20012 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse20012 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20012 input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Calories == input.Calories ||
                    (this.Calories != null &&
                    this.Calories.Equals(input.Calories))
                ) && 
                (
                    this.Carbs == input.Carbs ||
                    (this.Carbs != null &&
                    this.Carbs.Equals(input.Carbs))
                ) && 
                (
                    this.Fat == input.Fat ||
                    (this.Fat != null &&
                    this.Fat.Equals(input.Fat))
                ) && 
                (
                    this.Protein == input.Protein ||
                    (this.Protein != null &&
                    this.Protein.Equals(input.Protein))
                ) && 
                (
                    this.Bad == input.Bad ||
                    this.Bad != null &&
                    input.Bad != null &&
                    this.Bad.SequenceEqual(input.Bad)
                ) && 
                (
                    this.Good == input.Good ||
                    this.Good != null &&
                    input.Good != null &&
                    this.Good.SequenceEqual(input.Good)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Calories != null)
                {
                    hashCode = (hashCode * 59) + this.Calories.GetHashCode();
                }
                if (this.Carbs != null)
                {
                    hashCode = (hashCode * 59) + this.Carbs.GetHashCode();
                }
                if (this.Fat != null)
                {
                    hashCode = (hashCode * 59) + this.Fat.GetHashCode();
                }
                if (this.Protein != null)
                {
                    hashCode = (hashCode * 59) + this.Protein.GetHashCode();
                }
                if (this.Bad != null)
                {
                    hashCode = (hashCode * 59) + this.Bad.GetHashCode();
                }
                if (this.Good != null)
                {
                    hashCode = (hashCode * 59) + this.Good.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // Calories (string) minLength
            if (this.Calories != null && this.Calories.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Calories, length must be greater than 1.", new [] { "Calories" });
            }

            // Carbs (string) minLength
            if (this.Carbs != null && this.Carbs.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Carbs, length must be greater than 1.", new [] { "Carbs" });
            }

            // Fat (string) minLength
            if (this.Fat != null && this.Fat.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Fat, length must be greater than 1.", new [] { "Fat" });
            }

            // Protein (string) minLength
            if (this.Protein != null && this.Protein.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Protein, length must be greater than 1.", new [] { "Protein" });
            }

            yield break;
        }
    }

}
