/*
 * spoonacular API
 *
 * The spoonacular Nutrition, Recipe, and Food API allows you to access over 380,000 recipes, thousands of ingredients, 800,000 food products, and 100,000 menu items. Our food ontology and semantic recipe search engine makes it possible to search for recipes using natural language queries, such as \"gluten free brownies without sugar\" or \"low fat vegan cupcakes.\" You can automatically calculate the nutritional information for any recipe, analyze recipe costs, visualize ingredient lists, find recipes for what's in your fridge, find recipes based on special diets, nutritional requirements, or favorite ingredients, classify recipes into types and cuisines, convert ingredient amounts, or even compute an entire meal plan. With our powerful API, you can create many kinds of food and especially nutrition apps.  Special diets/dietary requirements currently available include: vegan, vegetarian, pescetarian, gluten free, grain free, dairy free, high protein, whole 30, low sodium, low carb, Paleo, ketogenic, FODMAP, and Primal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@spoonacular.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Spoonacular.Client.OpenAPIDateConverter;

namespace Spoonacular.Model
{
    /// <summary>
    /// RecipesParseIngredientsNutrition
    /// </summary>
    [DataContract(Name = "_recipes_parseIngredients_nutrition")]
    public partial class RecipesParseIngredientsNutrition : IEquatable<RecipesParseIngredientsNutrition>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RecipesParseIngredientsNutrition" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RecipesParseIngredientsNutrition() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RecipesParseIngredientsNutrition" /> class.
        /// </summary>
        /// <param name="nutrients">nutrients (required).</param>
        /// <param name="properties">properties (required).</param>
        /// <param name="flavonoids">flavonoids (required).</param>
        /// <param name="caloricBreakdown">caloricBreakdown (required).</param>
        /// <param name="weightPerServing">weightPerServing (required).</param>
        public RecipesParseIngredientsNutrition(List<RecipesParseIngredientsNutritionNutrients> nutrients = default(List<RecipesParseIngredientsNutritionNutrients>), List<RecipesParseIngredientsNutritionProperties> properties = default(List<RecipesParseIngredientsNutritionProperties>), List<RecipesParseIngredientsNutritionProperties> flavonoids = default(List<RecipesParseIngredientsNutritionProperties>), RecipesParseIngredientsNutritionCaloricBreakdown caloricBreakdown = default(RecipesParseIngredientsNutritionCaloricBreakdown), RecipesParseIngredientsNutritionWeightPerServing weightPerServing = default(RecipesParseIngredientsNutritionWeightPerServing))
        {
            // to ensure "nutrients" is required (not null)
            if (nutrients == null)
            {
                throw new ArgumentNullException("nutrients is a required property for RecipesParseIngredientsNutrition and cannot be null");
            }
            this.Nutrients = nutrients;
            // to ensure "properties" is required (not null)
            if (properties == null)
            {
                throw new ArgumentNullException("properties is a required property for RecipesParseIngredientsNutrition and cannot be null");
            }
            this.Properties = properties;
            // to ensure "flavonoids" is required (not null)
            if (flavonoids == null)
            {
                throw new ArgumentNullException("flavonoids is a required property for RecipesParseIngredientsNutrition and cannot be null");
            }
            this.Flavonoids = flavonoids;
            // to ensure "caloricBreakdown" is required (not null)
            if (caloricBreakdown == null)
            {
                throw new ArgumentNullException("caloricBreakdown is a required property for RecipesParseIngredientsNutrition and cannot be null");
            }
            this.CaloricBreakdown = caloricBreakdown;
            // to ensure "weightPerServing" is required (not null)
            if (weightPerServing == null)
            {
                throw new ArgumentNullException("weightPerServing is a required property for RecipesParseIngredientsNutrition and cannot be null");
            }
            this.WeightPerServing = weightPerServing;
        }

        /// <summary>
        /// Gets or Sets Nutrients
        /// </summary>
        [DataMember(Name = "nutrients", IsRequired = true, EmitDefaultValue = false)]
        public List<RecipesParseIngredientsNutritionNutrients> Nutrients { get; set; }

        /// <summary>
        /// Gets or Sets Properties
        /// </summary>
        [DataMember(Name = "properties", IsRequired = true, EmitDefaultValue = false)]
        public List<RecipesParseIngredientsNutritionProperties> Properties { get; set; }

        /// <summary>
        /// Gets or Sets Flavonoids
        /// </summary>
        [DataMember(Name = "flavonoids", IsRequired = true, EmitDefaultValue = false)]
        public List<RecipesParseIngredientsNutritionProperties> Flavonoids { get; set; }

        /// <summary>
        /// Gets or Sets CaloricBreakdown
        /// </summary>
        [DataMember(Name = "caloricBreakdown", IsRequired = true, EmitDefaultValue = false)]
        public RecipesParseIngredientsNutritionCaloricBreakdown CaloricBreakdown { get; set; }

        /// <summary>
        /// Gets or Sets WeightPerServing
        /// </summary>
        [DataMember(Name = "weightPerServing", IsRequired = true, EmitDefaultValue = false)]
        public RecipesParseIngredientsNutritionWeightPerServing WeightPerServing { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RecipesParseIngredientsNutrition {\n");
            sb.Append("  Nutrients: ").Append(Nutrients).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  Flavonoids: ").Append(Flavonoids).Append("\n");
            sb.Append("  CaloricBreakdown: ").Append(CaloricBreakdown).Append("\n");
            sb.Append("  WeightPerServing: ").Append(WeightPerServing).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RecipesParseIngredientsNutrition);
        }

        /// <summary>
        /// Returns true if RecipesParseIngredientsNutrition instances are equal
        /// </summary>
        /// <param name="input">Instance of RecipesParseIngredientsNutrition to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RecipesParseIngredientsNutrition input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Nutrients == input.Nutrients ||
                    this.Nutrients != null &&
                    input.Nutrients != null &&
                    this.Nutrients.SequenceEqual(input.Nutrients)
                ) && 
                (
                    this.Properties == input.Properties ||
                    this.Properties != null &&
                    input.Properties != null &&
                    this.Properties.SequenceEqual(input.Properties)
                ) && 
                (
                    this.Flavonoids == input.Flavonoids ||
                    this.Flavonoids != null &&
                    input.Flavonoids != null &&
                    this.Flavonoids.SequenceEqual(input.Flavonoids)
                ) && 
                (
                    this.CaloricBreakdown == input.CaloricBreakdown ||
                    (this.CaloricBreakdown != null &&
                    this.CaloricBreakdown.Equals(input.CaloricBreakdown))
                ) && 
                (
                    this.WeightPerServing == input.WeightPerServing ||
                    (this.WeightPerServing != null &&
                    this.WeightPerServing.Equals(input.WeightPerServing))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Nutrients != null)
                {
                    hashCode = (hashCode * 59) + this.Nutrients.GetHashCode();
                }
                if (this.Properties != null)
                {
                    hashCode = (hashCode * 59) + this.Properties.GetHashCode();
                }
                if (this.Flavonoids != null)
                {
                    hashCode = (hashCode * 59) + this.Flavonoids.GetHashCode();
                }
                if (this.CaloricBreakdown != null)
                {
                    hashCode = (hashCode * 59) + this.CaloricBreakdown.GetHashCode();
                }
                if (this.WeightPerServing != null)
                {
                    hashCode = (hashCode * 59) + this.WeightPerServing.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
